name: "SciOlyID Actions - Update Redis URL"
author: "Tomi Chen"
description: "Custom pipeline for deploying SciOlyID Bots"

branding:
  icon: "upload-cloud"
  color: "green"

inputs:
  dokku app name:
    description: "Name of dokku app"
    required: true
  dokku host:
    description: "IP or domain of dokku server"
    required: true
  ssh private key:
    description: "SSH private key to access dokku"
    required: true

  heroku email:
    description: "Email to access heroku account (see ~/.netrc)"
    required: false
  heroku token:
    description: "Token to access heroku account (see ~/.netrc)"
    required: false
  heroku app name:
    description: "Name of heroku app"
    required: false

runs:
  using: "docker"
  image: "Dockerfile"
