name: "SciOlyID Actions - Deploy to Dokku"
author: "Tomi Chen"
description: "Custom pipeline for deploying SciOlyID Bots"

branding:
  icon: "upload-cloud"
  color: "green"

inputs:
  dokku app name:
    description: "Name of dokku app"
    required: true
  dokku host:
    description: "IP or domain of dokku server"
    required: true
  ssh private key:
    description: "SSH private key to access dokku"
    required: true
  deploy branch:
    description: "Branch to deploy to"
    required: false
    default: "master"

runs:
  using: "docker"
  image: "Dockerfile"
